---
name: Install Dependencies
description: "Installs required Python packages"
runs:
  using: composite
  steps:
    - run: |
        python -m pip install --upgrade pip
        pip install -r required_libraries.txt
        pip install pytest
      shell: bash