---
name: Run Motivational Messages
description: "Runs motivational message"
inputs:
  command:
    description: "Motivational message to run"
    required: true
  user_key:
    description: "Pushover User Key"
    required: true
  token:
    description: "Pushover API Token"
    required: true
runs:
  using: composite
  steps:
    - run: |
        export PUSHOVER_USER_KEY=${{ inputs.user_key }}
        export PUSHOVER_API_TOKEN=${{ inputs.token }}
        go run main.go ${{ inputs.command }}
      shell: bash