---
name: Break Reminder

on:
  schedule:
    - cron: '0 20 * * 1-5'
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  CARRIER: ${{ secrets.CARRIER }}

jobs:
  send-break-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Create .env file
      uses: ./.github/actions/create-env-file
      with:
        user_key: ${{ secrets.PUSHOVER_USER_KEY }}
        token: ${{ secrets.PUSHOVER_API_TOKEN }}

    - name: Send break notification
      uses: ./.github/actions/run-command
      with:
        command: 'break'