---
name: Break Reminder

on:
  schedule:
    - cron: '0 20 * * 1-5'
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  CARRIER: ${{ secrets.CARRIER }}

jobs:
  send-break-sms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Send break SMS
      uses: ./.github/actions/run-command
      with:
        command: 'break'