---
name: End of Day Reminder

on:
  schedule:
    - cron: '0 1 * * 2-6'
  workflow_dispatch:

env:
  EMAIL: ${{ secrets.EMAIL }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  CARRIER: ${{ secrets.CARRIER }}

jobs:
  send-eod-sms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Send end of day SMS
      uses: ./.github/actions/run-command
      with:
        command: 'end_work_day'