---
name: End of Day Reminder

on:
  schedule:
    - cron: '10 1 * * 2-6'
  workflow_dispatch:

env:
  PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
  PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}

jobs:
  send-eod-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Create .env file
      uses: ./.github/actions/create-env-file
      with:
        user_key: ${{ env.PUSHOVER_USER_KEY }}
        token: ${{ env.PUSHOVER_API_TOKEN }}

    - name: Send end of day notification
      uses: ./.github/actions/run-command
      with:
        command: 'end_work_day'