---
name: Run Tests

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: "./go.mod"

    - name: Run tests
      run: go test -v ./...