---
name: Testing sms.py

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Create test .env file
      uses: ./.github/actions/create-env-file
    
    - name: Run unit tests
      run: |
        pytest -m "unit or integration" -v