name: Testing standup.py

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r required_libraries.txt
        pip install pytest
    
    - name: Create test .env file
      run: |
        echo "EMAIL=test@example.com" > src/.env
        echo "PASSWORD=test_password" >> src/.env
        echo "PHONE_NUMBER=5551234567" >> src/.env
        echo "CARRIER=verizon" >> src/.env
    
    - name: Run unit tests
      run: |
        pytest -m unit -v